language: rust

rust:
  - stable
  - beta
  - nightly

sudo: required

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo

before_script:
  - sudo apt-get install libgtk-3-dev libgtk-3-dev

script:
  - cargo test --verbose --workspace
